const STATES = Object.freeze({READY:'READY',RUNNING:'RUNNING',WAITING_REVIEW:'WAITING_REVIEW',CHANGES_REQUESTED:'CHANGES_REQUESTED',PASS:'PASS',BLOCKED:'BLOCKED',NEEDS_USER_DECISION:'NEEDS_USER_DECISION'});
module.exports={STATES};
